### ISSUE TITLE
Host Dashboard - 3 of the Brick panels are unclear what they are about

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#324] opened 2018-01-31 21:22 UTC
As mentioned in one of the comments in the [Host Dashboard Spec](https://github.com/Tendrl/specifications/issues/223#issuecomment-362070848), there are 3 panels that somewhat ambiguous what they intend to show the user.

![image](https://user-images.githubusercontent.com/5589919/35648098-9174754c-06a2-11e8-9ba5-2be018336913.png)

Specifically, are the 3 Panels (Brick Utilization, Brick Capacity, and Brick Capacity Used panels trying to actually showcase all the bricks on the host, or the top n bricks on the host, or something else? The labels for the panels don't tell a user one way or either what the intent was, nor is there accompanying description to help explain it.

My recommendation is it ought to be showing the Top Brick Consumers based on the 3 different criteria (total, utilized, % utilized) and in the following left-to-right order:

Brick Capacity (current panel name) --> Top Bricks by Total Capacity (suggested new panel name)
Brick Capacity Used (current panel name)--> Top Bricks by Capacity Utilized (suggested new panel name)
Brick Utilization (current panel name)--> Top Bricks by Capacity Percent Utilized (suggested new panel name)

@r0h4n @cloudbehl @fbalak @mcarrano @Tendrl/tendrl-qe

**Comment by nthomas-redhat** [comment] 2018-02-02 08:44
> Specifically, are the 3 Panels (Brick Utilization, Brick Capacity, and Brick Capacity Used panels trying to actually showcase all the bricks on the host, or the top n bricks on the host, or something else? The labels for the panels don't tell a user one way or either what the intent was, nor is there accompanying description to help explain it.
> 

Your assumption is correct; right now its showing total storage capacity available on that host(aggregate all capacity allocated for bricks), and the utilization(data and trend)

> My recommendation is it ought to be showing the Top Brick Consumers based on the 3 different criteria (total, utilized, % utilized) and in the following left-to-right order:
> 
> Brick Capacity (current panel name) --> Top Bricks by Total Capacity (suggested new panel name)

I am ok with this suggestion.

> Brick Capacity Used (current panel name)--> Top Bricks by Capacity Utilized (suggested new panel name)
> Brick Utilization (current panel name)--> Top Bricks by Capacity Percent Utilized (suggested new panel name)

@julienlim, How the above two panels are going to differ(Top Bricks by Capacity Utilized and Top Bricks by Capacity Percent Utilized)? I don't think it make a value add, if everyone is convinced we can get rid of one as well

**Comment by julienlim** [comment] 2018-02-02 14:39
@nthomas-redhat 

With regards to Top Bricks by Capacity Utilized and Top Bricks by Capacity Percent Utilized, yes they are similar, but it's just looking at it from different perspectives.

Let's say the 2 highest capacity utilized bricks is as follow:
* 85% utilized 1TB brick (~150GB remaining)
* 85% utilized 100GB brick (~15GB remaining)

In looking at these 2, the 85% only tells us where to focus on, but when the user has to prioritize which one to take action on first, user will look at growth trend of the brick to see which one is growing faster, as well as which one has less space in order to take action first.  Specifically, if we assume both bricks are growing roughly at the same rate, the 15 GB remaining brick will run out of space sooner (probably before the brick with 150 GB remaining).

I thought about combining them, e.g. /brickpath, % utilized, capacity remaining (or capacity utilized), but it would look a bit odd with the white space there, so I figured to leave them separated for now until we have more panels to fill the spot (or until we do rearranging of the panels).

**Comment by nthomas-redhat** [comment] 2018-02-07 12:42
Ack

**Comment by cloudbehl** [comment] 2018-02-26 05:02
@julienlim The Issue is fixed in upstream, can you please verify this bug.

**Comment by nthomas-redhat** [comment] 2018-03-21 17:59
Closing as the fix is already in

**Closed by nthomas-redhat** 2018-03-21 17:59 UTC
