### ISSUE TITLE
No alerts for when capacity utilization threshold breached

### ISSUE THREAD

**Issue by julienlim** [Tendrl/monitoring-integration#194] opened 2017-10-11 20:25 UTC
I redeployed tendrl using tendrl-ansible from master just now, and I created a near full condition on one of my bricks, and no alerts to say that threshold was breach on node 3:/bricks/brick1 were generated.  

I also noticed that in the Tendrl UI, the chart shown the brick utilization shows blue (which may confuse user who sees it differently in the Grafana dashboards since it is not matching the thresholds colors used in the Host dashboards.

<img width="1231" alt="screen shot 2017-10-11 at 4 23 15 pm" src="https://user-images.githubusercontent.com/5589919/31465063-d619d44e-aea0-11e7-9a95-943a3b5c8774.png">

<img width="1232" alt="screen shot 2017-10-11 at 4 21 00 pm" src="https://user-images.githubusercontent.com/5589919/31465028-bb42209a-aea0-11e7-86dd-00a97599b3f9.png">

<img width="584" alt="screen shot 2017-10-11 at 4 21 29 pm" src="https://user-images.githubusercontent.com/5589919/31465031-beea69fa-aea0-11e7-8fe4-4715623003ac.png">

<img width="1231" alt="screen shot 2017-10-11 at 4 23 54 pm" src="https://user-images.githubusercontent.com/5589919/31465055-d27936fe-aea0-11e7-9690-01ff31110e30.png">

<img width="1234" alt="screen shot 2017-10-11 at 4 27 11 pm" src="https://user-images.githubusercontent.com/5589919/31465157-142849fa-aea1-11e7-8692-a99d2d1781a6.png">

@cloudbehl @gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by rishubhjain** [comment] 2017-10-17 08:56
@cloudbehl Please check the issue.

**Comment by cloudbehl** [comment] 2017-10-23 06:37
@GowthamShanmugam Can you verify why the bricks alert is generated when the threshold is breached.

@gnehapk Is the color coding added in the progress bar if the utilization exceeds 80% it should be yellow and when it exceeds 90% it should be Red.

**Comment by GowthamShanmugam** [comment] 2017-10-23 12:43
@cloudbehl verified, it works fine, need to merge this small PR to receive volume alerts from grafana https://github.com/Tendrl/monitoring-integration/pull/217

**Comment by rishubhjain** [comment] 2017-10-26 07:24
@julienlim Please verify whether the issue is still reproducible or not.

**Comment by GowthamShanmugam** [comment] 2017-10-26 07:45
@rishubhjain need this patch to be merged for this it will solve all alert count and alert filter and grafana volume alert catch 

https://github.com/Tendrl/monitoring-integration/pull/219
https://github.com/Tendrl/gluster-integration/pull/453
https://github.com/Tendrl/commons/pull/766
https://github.com/Tendrl/node-agent/pull/657

**Comment by GowthamShanmugam** [comment] 2017-10-31 12:45
@julienlim This issue is fixed, please verify this

**Comment by julienlim** [comment] 2017-11-03 17:25
@GowthamShanmugam @rishubhjain @cloudbehl @gnehapk Verified that when I caused one of the bricks threshold to breach that an alert was generated.
<img width="1123" alt="screen shot 2017-11-03 at 1 15 34 pm" src="https://user-images.githubusercontent.com/5589919/32387135-dc910dbe-c099-11e7-8145-3ead50fb920e.png">

Observing that the alerts counter on hosts is not correctly synchronizing with the alerts (as node2 should have 2 vs. 1 alert).
<img width="1124" alt="screen shot 2017-11-03 at 1 16 15 pm" src="https://user-images.githubusercontent.com/5589919/32387176-0918b3a0-c09a-11e7-96c0-cd473ee327b9.png">

I checked the vol1 (which node2:/bricks/brick1 is on that breached), the vol1 alert counter was incremented to 1.
<img width="1123" alt="screen shot 2017-11-03 at 1 16 31 pm" src="https://user-images.githubusercontent.com/5589919/32387204-1f990030-c09a-11e7-8e26-d7299af25144.png">

My environment:
* Tendrl 1.5.4 deployed
* Tendrl server on node0
* Tendrl node-agents on node1, node2, node3 -- node1-3 are in the same Gluster cluster

I filled up node2:/bricks/brick1 to over 90% to trigger a threshold breach.  Threshold alert did occur.  Other alerts for node1, node2, node3 also triggered based on memory utilization above 80%.

@Tendrl/tendrl-qe

**Comment by GowthamShanmugam** [comment] 2017-11-04 12:20
@julienlim memory utilization node2 is very near to max threshold breach of 80.4 so it might be replaced with the clear event before you check alert count, because it may come less than 80 before you check, please past the notification UI screen also. then we can verify easily.

**Comment by julienlim** [comment] 2017-11-06 14:23
@GowthamShanmugam 

Here's the alerts & notification screenshot along with host list:

![screen shot 2017-11-06 at 9 17 20 am](https://user-images.githubusercontent.com/5589919/32445406-9987de3a-c2d3-11e7-82bc-73446065976a.png)

![screen shot 2017-11-06 at 9 17 30 am](https://user-images.githubusercontent.com/5589919/32445411-9caa3360-c2d3-11e7-94c2-e91f90abe08d.png)

**Comment by GowthamShanmugam** [comment] 2017-11-06 15:10
@Tendrl/tendrl-core is brick utilization threshold breach also should come under node alert count? I have added only brick down in node alert counts. 

i am sure brick utilization threshold breach should not come under volume alert count, is it related necessary to add in node_alert count ?

**Comment by shtripat** [comment] 2017-11-10 05:47
@nthomas-redhat @brainfunked @r0h4n plz comment.
I feel its good to have node level alert count if brick utilization breached threshold.

**Comment by r0h4n** [comment] 2017-11-17 17:58
I would suggest we track the new change requests in a separate issue.

**Closed by r0h4n** 2017-11-17 17:58 UTC

**Comment by julienlim** [comment] 2017-11-20 14:41
@r0h4n Can you please list what the GitHub issues are so I can track them?
