### ISSUE TITLE
stopped volume status in Grafana

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/monitoring-integration#23] opened 2017-08-10 14:05 UTC
Grafana says `Degraded` for any stopped volume. But for volume to be degraded it has to fulfill:

>  UP(Degraded) This state is specific to replicated volumes, where at least one brick is down within a replica set. Data is still 100% available due to the alternate replica(s),  but the resilience of the volume to further failures within the same replica set flags this volume as 'degraded'.
<br>
<br>
E.g.

Grafana says `Degraded` whilst `# gstatus -a` prints:
```
Volumes:
	             0 Up
	             0 Up(Degraded)
	             0 Up(Partial)
                     1 Down
```

`gluster volume info` says:
```
Status: Stopped
```
or
```
Status: Created
```

**Comment by ltrilety** [comment] 2017-08-10 14:10
After some time the status was changed to `Stopped` as it should be.

**Comment by rishubhjain** [comment] 2017-09-26 08:23
@ltrilety The PR required to solve this issue is merged, can you verify whether the issue is resolved or not?
cc @shtripat

**Comment by nthomas-redhat** [comment] 2017-10-06 10:43
Closing this as it is verified

**Closed by nthomas-redhat** 2017-10-06 10:43 UTC
