### ISSUE TITLE
grafana doesn't show properly rebalance info

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/monitoring-integration#166] opened 2017-10-04 16:34 UTC
After rebalance I see this info
```
$ gluster volume rebalance volume_usmqe_alpha_distrep_4x2 status
                                    Node Rebalanced-files          size       scanned      failures       skipped               status  run time in h:m:s
                               ---------      -----------   -----------   -----------   -----------   -----------         ------------     --------------
                               localhost                0        0Bytes            15             0             0            completed        0:00:00
mkudlej-usm2-gl2.usmqe.lab.eng.blr.redhat.com                0        0Bytes            15             0             0            completed        0:00:00
mkudlej-usm2-gl3.usmqe.lab.eng.blr.redhat.com                0        0Bytes            23             0             0            completed        0:00:00
mkudlej-usm2-gl4.usmqe.lab.eng.blr.redhat.com                0        0Bytes            23             0             0            completed        0:00:00
mkudlej-usm2-gl5.usmqe.lab.eng.blr.redhat.com                1         1.0GB            12             0             1            completed        0:00:27
mkudlej-usm2-gl6.usmqe.lab.eng.blr.redhat.com                2         2.0GB            12             0             1            completed        0:01:10
volume rebalance: volume_usmqe_alpha_distrep_4x2: success

```
but there is wrong info in Grafana, see screenshot.

![bug_rebalance](https://user-images.githubusercontent.com/5920442/31187431-2ea7649c-a932-11e7-8065-4facae3cbc26.png)

And sometimes there is some data but it is not correct.
![bug_rebalance1](https://user-images.githubusercontent.com/5920442/31187585-9ff23d0c-a932-11e7-919b-6f7fab5e431c.png)

**Comment by mkudlej** [comment] 2017-10-04 16:36
I've forgotten to ad set of packages:
```
etcd-3.2.5-1.el7.x86_64
grafana-4.5.2-1.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-gluster-integration-1.5.2-20171004T141256.07ceba5.noarch
tendrl-grafana-plugins-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-monitoring-integration-1.5.2-20171004T072405.2e1d15a.noarch
tendrl-node-agent-1.5.2-20171004T105957.709badc.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
```

**Comment by anmolbabu** [comment] 2017-10-05 07:54
The issue is that the key for rebalance related counters in get-state o/p(ex: volume1.rebalance.failures) although seems to appear as if it were an aggregate data applying at the volume level, it actually infact applies to node on which get-state cmd is run but for a particular volume level. This was mis-interpreted by collectd to be an info at volume level as the key suggests.

An issue to fix this on collectd side has been created at https://github.com/Tendrl/node-agent/issues/638

Now, given the fix on collectd plugin, the question now is since this value is shown at volume dashboard, should it be average of rebalance stats for each of the volume nodes in the volume dashboard  or node wise separate graphs for the volume in volume dashboard? or should we show it volume-wise on a node dashboard ?

**Comment by nthomas-redhat** [comment] 2017-10-06 07:50
@anmolbabu , As per our discussion collectd can push the node level rebalance data to graphite and then grafana should run a sum query to get aggregate volume level stats. In summary we need to sum up all node level data to get volume level stats.
@shtripat @brainfunked ^

**Comment by shtripat** [comment] 2017-10-06 08:22
@nthomas-redhat I agree as the details like `rebalanced_files`, `rebalanced_size`, `skipped` and `failed` are sum for all the nodes at volume level.

The estimated time to complete and overall rebalance status at volume level is already taken care by gluster-integration and available at volume level in etcd.

**Comment by cloudbehl** [comment] 2017-10-08 16:47
@anmolbabu Do let me know when the changes are done, will need a name.

**Comment by anmolbabu** [comment] 2017-10-09 05:43
@cloudbehl Changes are done and merged(on Saturday - 2 days ago) from collectd side. Please do the needful as per the comments above.

The new graphite table name for rebalance data are:

1. tendrl.clusters.{cluster_id}.volumes.{volume_name}.nodes.{node_name}.rebalance_bytes
2. tendrl.clusters.{cluster_id}.volumes.{volume_name}.nodes.{node_name}.rebalance_files
3. tendrl.clusters.{cluster_id}.volumes.{volume_name}.nodes.{node_name}.rebalance_failures
4. tendrl.clusters.{cluster_id}.volumes.{volume_name}.nodes.{node_name}.rebalance_skipped

**Closed** 2017-11-10 05:53 UTC
