### ISSUE TITLE
Brick Utilization: threshold breached Alert needs to reference gluster volume name

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/monitoring-integration#348] opened 2018-02-28 09:13 UTC
When a gluster volume usage goes above 75% an Alert is generated with only the brick volume group with no easy way to reference back to the gluster volume name. This is a big issue for CRS and OpenShift. If a gluster volume goes above 75% the only way to map to OCP Persistent Volume name is via the gluster volume name, not the brick or volume group name. 

Steps to Reproduce:
1.Identify gluster volume and write data into volume to exceed 75% threshold. 
2.Tendrl Alert should be generated for all bricks in the volumes
3.Alert will look something like below (have removed actual gluster server hostname because Alert is from customer tendrl installation). In the case of CRS 3 Alerts will be generated and sent to specified email address, one for each brick.
Brick utilization of <gluster_server_hostname>:|var|lib|heketi|mounts|vg_0bfd0da65ef15a9d75692a67b838cfc9|brick_c5e7ee1e0704c91888f04cfb4cb50017|brick in cluster 7bc6aa73-0c97-404b-88a2-077b5c77656a is 82.29 % which is above WARNING threshold (75 %)
4. No easy way to track to what gluster volume these Alerts are associated with.

**Comment by GowthamShanmugam** [comment] 2018-03-21 09:54
This issue is fixed, please verify and close this issue

**Comment by GowthamShanmugam** [comment] 2018-03-21 10:25
Tendrl/monitoring-integration/pull/385

**Comment by nthomas-redhat** [comment] 2018-03-21 13:10
Duplicate of https://github.com/Tendrl/monitoring-integration/issues/384
Closing the issue

**Closed by nthomas-redhat** 2018-03-21 13:10 UTC
