### ISSUE TITLE
Duplicated Volumes in Grafana

### ISSUE THREAD

**Issue by dahorak** [Tendrl/monitoring-integration#159] opened 2017-10-03 12:32 UTC
Gluster volumes containing upper case letters are duplicated in Grafana - once with original name, second time in lover case.

```
# gluster volume list
TestVolumeB
TestVolumeC
volume_usmqe_alpha_distrep_4x2
```

![grafana_duplicated_volumes](https://user-images.githubusercontent.com/4759779/31125075-5f14f400-a847-11e7-8302-049397a65af8.png)

```
tendrl-ansible-1.5.3-20170927T210232.29c6d57.noarch
tendrl-api-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-api-httpd-1.5.2-20170927T205654.a9e16c0.noarch
tendrl-commons-1.5.2-20170928T094225.e83ddf7.noarch
tendrl-grafana-plugins-1.5.2-20171003T072405.2e1d15a.noarch
tendrl-monitoring-integration-1.5.2-20171003T072405.2e1d15a.noarch
tendrl-node-agent-1.5.2-20170928T123732.dfcaddf.noarch
tendrl-notifier-1.5.2-20170927T205657.566bfa0.noarch
tendrl-ui-1.5.2-20170928T151925.1cdc907.noarch
```
```
tendrl-commons-1.5.2-20170928T094225.e83ddf7.noarch
tendrl-gluster-integration-1.5.2-20171003T062306.f428920.noarch
tendrl-node-agent-1.5.2-20170928T123732.dfcaddf.noarch
```

**Comment by rishubhjain** [comment] 2017-10-04 12:31
@dahorak The graphite might be populated with lower case volume name, If possible please provide tendrl-server ip, I would like to check graphite details. Also did you create any other volumes with such names in past?

**Comment by dahorak** [comment] 2017-10-04 13:02
Now it seems, it might be related only to volumes created after the Gluster cluster is imported into Tendrl.

**Comment by rishubhjain** [comment] 2017-10-05 05:43
@dahorak I looked up graphite, it seems you had created TestVolumeB and TestVolumeC in the past and deleted those volumes, deleting volume from gluster cluster doesn't remove volume from graphite because of which you are able to see that volume in grafana.
We are aware of this issue(resource details remain in graphite even after resource getting deleted from gluster cluster), and have sent a patch to solve this issue.

**Comment by dahorak** [comment] 2017-10-05 06:42
> Now it seems, it might be related only to volumes created after the Gluster cluster is imported into Tendrl.
This assumption was wrong, it probably takes some time, but it apply to all volumes containing upper case letters, no matter when they were created.

**Comment by dahorak** [comment] 2017-10-05 06:43
@rishubhjain I didn't delete any Volume, the volumes are still present:

```
# gluster volume list
TestVolumeB
TestVolumeC
volume_usmqe_alpha_distrep_4x2
```

**Comment by rishubhjain** [comment] 2017-10-06 12:11
@dahorak The volumes with both uppercase and lowercase letters are present in graphite as well. So in my opinion the volumes existed in the past because of which there is an entry in graphite.
Can you reproduce this on a fresh setup?. Or provide me access to your machine I would like to debug more

**Comment by dahorak** [comment] 2017-10-06 12:23
@rishubhjain I didn't remove any volume there (only the three volumes which are visible from the gluster command were created).
I can easily reproduce it, simply create gluster volume and name it with some upper case letters.

**Comment by rishubhjain** [comment] 2017-10-17 09:07
@dahorak Please verify and close the issue

**Closed** 2017-10-26 08:53 UTC
