### ISSUE TITLE
volume status is not valid

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/monitoring-integration#191] opened 2017-10-11 11:54 UTC
I've imported cluster and look at grafana dashboard for only one volume there and there are these issue:
1) Volume is *up(degraded)* even if I see in Gluster CLI that volume is *up*.
2) *Rebalance status* chart shows that it is *In progress* even if Gluster CLI command shows different ifo
![bug_volume_status](https://user-images.githubusercontent.com/5920442/31439145-681ef8ee-ae8b-11e7-9450-7dc579e72396.png)

If information is not available for volume chart should be properly marked that there is not info for this chart.

**Comment by mkudlej** [comment] 2017-10-11 12:21
I've forgotten to mention important info:
```
$ gluster volume rebalance volume_gama_disperse_4_plus_2x2 status
volume rebalance: volume_gama_disperse_4_plus_2x2: failed: Rebalance not started for volume volume_gama_disperse_4_plus_2x2.
$ gluster volume status volume_gama_disperse_4_plus_2x2
Status of volume: volume_gama_disperse_4_plus_2x2
Gluster process                             TCP Port  RDMA Port  Online  Pid
------------------------------------------------------------------------------
Brick mkudlej-usm1-gl1.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1635 
Brick mkudlej-usm1-gl2.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1458 
Brick mkudlej-usm1-gl3.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1491 
Brick mkudlej-usm1-gl4.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1506 
Brick mkudlej-usm1-gl5.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1499 
Brick mkudlej-usm1-gl6.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_1/1       49152     0          Y       1530 
Brick mkudlej-usm1-gl1.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1644 
Brick mkudlej-usm1-gl2.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1470 
Brick mkudlej-usm1-gl3.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1500 
Brick mkudlej-usm1-gl4.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1505 
Brick mkudlej-usm1-gl5.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1508 
Brick mkudlej-usm1-gl6.usmqe.lab.eng.brq.re
dhat.com:/mnt/brick_gama_disperse_2/2       49153     0          Y       1544 
Self-heal Daemon on localhost               N/A       N/A        Y       1424 
Self-heal Daemon on mkudlej-usm1-gl6.usmqe.
lab.eng.brq.redhat.com                      N/A       N/A        Y       1268 
Self-heal Daemon on mkudlej-usm1-gl3.usmqe.
lab.eng.brq.redhat.com                      N/A       N/A        Y       1258 
Self-heal Daemon on mkudlej-usm1-gl4.usmqe.
lab.eng.brq.redhat.com                      N/A       N/A        Y       1245 
Self-heal Daemon on mkudlej-usm1-gl2.usmqe.
lab.eng.brq.redhat.com                      N/A       N/A        Y       1244 
Self-heal Daemon on mkudlej-usm1-gl5.usmqe.
lab.eng.brq.redhat.com                      N/A       N/A        Y       1245 
 
Task Status of Volume volume_gama_disperse_4_plus_2x2
------------------------------------------------------------------------------
There are no active volume tasks

$ gluster volume info volume_gama_disperse_4_plus_2x2
 
Volume Name: volume_gama_disperse_4_plus_2x2
Type: Distributed-Disperse
Volume ID: e820fe96-ab41-4092-bf62-9a17a97ed2ae
Status: Started
Snapshot Count: 0
Number of Bricks: 2 x (4 + 2) = 12
Transport-type: tcp
Bricks:
Brick1: mkudlej-usm1-gl1.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick2: mkudlej-usm1-gl2.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick3: mkudlej-usm1-gl3.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick4: mkudlej-usm1-gl4.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick5: mkudlej-usm1-gl5.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick6: mkudlej-usm1-gl6.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_1/1
Brick7: mkudlej-usm1-gl1.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Brick8: mkudlej-usm1-gl2.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Brick9: mkudlej-usm1-gl3.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Brick10: mkudlej-usm1-gl4.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Brick11: mkudlej-usm1-gl5.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Brick12: mkudlej-usm1-gl6.usmqe.lab.eng.brq.redhat.com:/mnt/brick_gama_disperse_2/2
Options Reconfigured:
diagnostics.count-fop-hits: on
diagnostics.latency-measurement: on
nfs.disable: on
transport.address-family: inet
```
So info on Grafana dashboard is wrong.

**Comment by rishubhjain** [comment] 2017-10-13 08:07
@mkudlej I am trying to reproduce the up(degraded) issue, but the above patch has solved the issue with In Progress

**Comment by rishubhjain** [comment] 2017-10-17 09:00
@mkudlej If possible could you check whether you are able to reproduce this(volume status as "UP(degraded)") issue?

**Comment by mkudlej** [comment] 2017-10-19 14:25
This issue cannot be verify because https://github.com/Tendrl/monitoring-integration/issues/145 is not fixed.

**Comment by cloudbehl** [comment] 2017-11-10 05:50
@mkudlej This Issue is fixed. can you please verify.

**Comment by r0h4n** [comment] 2017-11-17 17:57
Closing since not verified by reporter since a week

**Closed by r0h4n** 2017-11-17 17:57 UTC
Labels: pending verification
