### ISSUE TITLE
No module named cliutils.cliutils

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [Tendrl/monitoring-integration#281] opened 2017-11-21 08:35 UTC
I was trying to setup tendrl using tendrl-ansible.

But , tendrl-monitoring-integration failed with following error:
`[root@tendrlserver ~]# tendrl-monitoring-integration 
Creating namespace.monitoring from source tendrl.monitoring_integration
namespace.monitoring created!
Finding objects in namespace.monitoring.objects
Registering object namespace.monitoring.objects.AlertTypes
Finding atoms in namespace.monitoring.objects.AlertTypes.atoms
Finding flows in namespace.monitoring.objects.AlertTypes.flows
Registering object namespace.monitoring.objects.Config
Finding atoms in namespace.monitoring.objects.Config.atoms
Finding flows in namespace.monitoring.objects.Config.flows
Registering object namespace.monitoring.objects.Definition
Finding atoms in namespace.monitoring.objects.Definition.atoms
Finding flows in namespace.monitoring.objects.Definition.flows
Registering object namespace.monitoring.objects.Trigger
Finding atoms in namespace.monitoring.objects.Trigger.atoms
Finding flows in namespace.monitoring.objects.Trigger.flows
Finding flows in namespace.monitoring.flows
Registering flow namespace.monitoring.flows.DeleteResourceFromGraphite
Registering flow namespace.monitoring.flows.UpdateDashboard
Setup Tendrl definitions (.yml)for namespace.monitoring
Validating registered (.py) flows in namespace.monitoring.flows
Validating defined (.yml) flows in namespace.monitoring.flows
Validating registered (.py) objects in namespace.monitoring.objects
Validating defined (.yml) objects in namespace.monitoring.objects
Setup Config for namespace.monitoring
Setup central store clients for namespace.monitoring
Creating namespace.tendrl from source tendrl.commons
namespace.tendrl created!
Finding objects in namespace.tendrl.objects
Registering object namespace.tendrl.objects.Alert
Finding atoms in namespace.tendrl.objects.Alert.atoms
Finding flows in namespace.tendrl.objects.Alert.flows
Registering object namespace.tendrl.objects.BlockDevice
Finding atoms in namespace.tendrl.objects.BlockDevice.atoms
Finding flows in namespace.tendrl.objects.BlockDevice.flows
Registering object namespace.tendrl.objects.Cluster
Finding atoms in namespace.tendrl.objects.Cluster.atoms
Registering atom namespace.tendrl.objects.Cluster.atoms.CheckClusterAvailable
Registering atom namespace.tendrl.objects.Cluster.atoms.ConfigureMonitoring
Registering atom namespace.tendrl.objects.Cluster.atoms.Create
Registering atom namespace.tendrl.objects.Cluster.atoms.ImportCluster
Registering atom namespace.tendrl.objects.Cluster.atoms.ImportCreatedCluster
Registering atom namespace.tendrl.objects.Cluster.atoms.PersistClusterDetailsAfterCreate
Registering atom namespace.tendrl.objects.Cluster.atoms.ValidCreateClusterParams
Registering atom namespace.tendrl.objects.Cluster.atoms.ValidImportClusterParams
Finding flows in namespace.tendrl.objects.Cluster.flows
Registering object namespace.tendrl.objects.Alert
Finding atoms in namespace.tendrl.objects.Alert.atoms
Finding flows in namespace.tendrl.objects.Alert.flows
Registering object namespace.tendrl.objects.ClusterAlert
Finding atoms in namespace.tendrl.objects.ClusterAlert.atoms
Finding flows in namespace.tendrl.objects.ClusterAlert.flows
Registering object namespace.tendrl.objects.ClusterAlertCounters
Finding atoms in namespace.tendrl.objects.ClusterAlertCounters.atoms
Finding flows in namespace.tendrl.objects.ClusterAlertCounters.flows
Registering object namespace.tendrl.objects.ClusterNodeContext
Finding atoms in namespace.tendrl.objects.ClusterNodeContext.atoms
Finding flows in namespace.tendrl.objects.ClusterNodeContext.flows
Registering object namespace.tendrl.objects.ClusterTendrlContext
Finding atoms in namespace.tendrl.objects.ClusterTendrlContext.atoms
Finding flows in namespace.tendrl.objects.ClusterTendrlContext.flows
Registering object namespace.tendrl.objects.Cpu
Finding atoms in namespace.tendrl.objects.Cpu.atoms
Finding flows in namespace.tendrl.objects.Cpu.flows
Registering object namespace.tendrl.objects.Definition
Finding atoms in namespace.tendrl.objects.Definition.atoms
Finding flows in namespace.tendrl.objects.Definition.flows
Registering object namespace.tendrl.objects.DetectedCluster
Finding atoms in namespace.tendrl.objects.DetectedCluster.atoms
Finding flows in namespace.tendrl.objects.DetectedCluster.flows
Registering object namespace.tendrl.objects.Disk
Finding atoms in namespace.tendrl.objects.Disk.atoms
Finding flows in namespace.tendrl.objects.Disk.flows
Registering object namespace.tendrl.objects.Job
Finding atoms in namespace.tendrl.objects.Job.atoms
Finding flows in namespace.tendrl.objects.Job.flows
Registering object namespace.tendrl.objects.Memory
Finding atoms in namespace.tendrl.objects.Memory.atoms
Finding flows in namespace.tendrl.objects.Memory.flows
Registering object namespace.tendrl.objects.Node
Finding atoms in namespace.tendrl.objects.Node.atoms
Registering atom namespace.tendrl.objects.Node.atoms.BaseAtom
Registering atom namespace.tendrl.objects.Node.atoms.CheckNodeUp
Registering atom namespace.tendrl.objects.Node.atoms.BaseAtom
Registering atom namespace.tendrl.objects.Node.atoms.Cmd
Registering atom namespace.tendrl.objects.Node.atoms.IsNodeTendrlManaged
Finding flows in namespace.tendrl.objects.Node.flows
Registering object namespace.tendrl.objects.Alert
Finding atoms in namespace.tendrl.objects.Alert.atoms
Finding flows in namespace.tendrl.objects.Alert.flows
Registering object namespace.tendrl.objects.NodeAlert
Finding atoms in namespace.tendrl.objects.NodeAlert.atoms
Finding flows in namespace.tendrl.objects.NodeAlert.flows
Registering object namespace.tendrl.objects.NodeAlertCounters
Finding atoms in namespace.tendrl.objects.NodeAlertCounters.atoms
Finding flows in namespace.tendrl.objects.NodeAlertCounters.flows
Registering object namespace.tendrl.objects.NodeContext
Finding atoms in namespace.tendrl.objects.NodeContext.atoms
Finding flows in namespace.tendrl.objects.NodeContext.flows
Registering object namespace.tendrl.objects.NodeNetwork
Finding atoms in namespace.tendrl.objects.NodeNetwork.atoms
Finding flows in namespace.tendrl.objects.NodeNetwork.flows
Registering object namespace.tendrl.objects.Alert
Finding atoms in namespace.tendrl.objects.Alert.atoms
Finding flows in namespace.tendrl.objects.Alert.flows
Registering object namespace.tendrl.objects.NotificationOnlyAlert
Finding atoms in namespace.tendrl.objects.NotificationOnlyAlert.atoms
Finding flows in namespace.tendrl.objects.NotificationOnlyAlert.flows
Registering object namespace.tendrl.objects.Os
Finding atoms in namespace.tendrl.objects.Os.atoms
Finding flows in namespace.tendrl.objects.Os.flows
Registering object namespace.tendrl.objects.Platform
Finding atoms in namespace.tendrl.objects.Platform.atoms
Finding flows in namespace.tendrl.objects.Platform.flows
Registering object namespace.tendrl.objects.Service
Finding atoms in namespace.tendrl.objects.Service.atoms
Registering atom namespace.tendrl.objects.Service.atoms.BaseAtom
Registering atom namespace.tendrl.objects.Service.atoms.CheckServiceStatus
Finding flows in namespace.tendrl.objects.Service.flows
Registering object namespace.tendrl.objects.TendrlContext
Finding atoms in namespace.tendrl.objects.TendrlContext.atoms
Finding flows in namespace.tendrl.objects.TendrlContext.flows
Registering object namespace.tendrl.objects.Disk
Finding atoms in namespace.tendrl.objects.Disk.atoms
Finding flows in namespace.tendrl.objects.Disk.flows
Registering object namespace.tendrl.objects.VirtualDisk
Finding atoms in namespace.tendrl.objects.VirtualDisk.atoms
Finding flows in namespace.tendrl.objects.VirtualDisk.flows
Finding flows in namespace.tendrl.flows
Registering flow namespace.tendrl.flows.AuthorizeSshKey
Registering flow namespace.tendrl.flows.ConfigureMonitoring
Registering flow namespace.tendrl.flows.CreateCluster
Registering flow namespace.tendrl.flows.ExpandCluster
Registering flow namespace.tendrl.flows.ImportCluster
Registering flow namespace.tendrl.flows.SetupSsh
Setup Tendrl definitions (.yml)for namespace.tendrl
Validating registered (.py) flows in namespace.tendrl.flows
Validating defined (.yml) flows in namespace.tendrl.flows
Validating registered (.py) objects in namespace.tendrl.objects
Validating defined (.yml) objects in namespace.tendrl.objects
Setup NodeContext for namespace.tendrl
Load definitions (.yml) for namespace.tendrl.objects.NodeContext 
Load definitions (.yml) for namespace.tendrl.objects.TendrlContext 
Traceback (most recent call last):
  File "/usr/bin/tendrl-monitoring-integration", line 9, in <module>
    load_entry_point('tendrl-monitoring-integration==1.5.4', 'console_scripts', 'tendrl-monitoring-integration')()
  File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 177, in main
    monitoring_integration_manager = MonitoringIntegrationManager()
  File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/manager/__init__.py", line 40, in __init__
    self.webhook_receiver = webhook_receiver.WebhookReceiver()
  File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/grafana/webhook_receiver.py", line 20, in __init__
    self.alert_handler = AlertHandlerManager()
  File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/alert/handlers/__init__.py", line 94, in __init__
    self._load_handlers()
  File "/usr/lib/python2.7/site-packages/tendrl/monitoring_integration/alert/handlers/__init__.py", line 73, in _load_handlers
    mod = importlib.import_module(handler_fqdn)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named cliutils.cliutils
[root@tendrlserver ~]#`

Issue is  I have python2-gluster-3.12.1-2.el7.x86_64 installed at tendrl-server node.

Once I remove /usr/lib/python2.7/site-packages/gluster/ directory. I can run tendrl-monitoring-integration.

I think there is some conflict between clituils referred in the above python code and python2-gluster package.
Please check. 
@GowthamShanmugam @nthomas-redhat

**Comment by nixpanic** [comment] 2017-11-21 13:35
I am not really sure what the problem above is, the traceback does not show sufficient detail to me. However I can explain how python-gluster is expected to interact with other components.

RPMs only allow contents to be part of a single package. The `.../site-packages/gluster` namespace is provided by python-gluster (the directory and the `__init__.py` file). Other projects that add more packages in the `.../site-packages/gluster` namespace, are expected to depend on the python-gluster RPM. If other RPMs expect to be the owner of `.../site-packages/gluster` or its `__init__.py` file, installation of those RPMs will likely fail when python-gluster is installed.

Note that `.../site-packages/gluster/cliutils` is provided by python-gluster since [a long time](http://review.gluster.org/14627). If, or how this refers to `ImportError: No module named cliutils.cliutils` is not clear to me.

**Comment by SaravanaStorageNetwork** [comment] 2017-11-22 04:48
@nixpanic  I think there is another cliutils module which clashes with python-gluster. 
Tendrl team is working on this

@GowthamShanmugam @nthomas-redhat  FYI

**Comment by GowthamShanmugam** [comment] 2017-11-22 06:20
The problem is in tendrl we are maintaining in alert handlers in monitoring-integration-component
handlers are maintained in two different directories 
    1. node - all node related alert handlers
    2. Cluster - all cluster related alert handlers  
              In cluster directory, there is a subdirectory called "gluster", this directory contains all gluster related alert handlers. Here the problem is folder name. While importing this gluster directory python  try to import gluster directory which contains all glusterfs files.  So the import exception is raised.

**Comment by SaravanaStorageNetwork** [comment] 2017-11-29 13:04
> In cluster directory, there is a subdirectory called "gluster", this directory contains all gluster related alert handlers. 

@GowthamShanmugam  Could you rename the folder name then ?

**Comment by GowthamShanmugam** [comment] 2018-01-10 06:21
We can change folder, no issue, i will change it

**Comment by GowthamShanmugam** [comment] 2018-01-10 06:28
Currently, we are not suporting to install gluster on a tendrl serve, @nthomas-redhat is this is a valid issue?

**Comment by SaravanaStorageNetwork** [comment] 2018-01-10 06:43
@GowthamShanmugam  @nthomas-redhat  I think it is a valid issue. Any specific reason to not support gluster install on a tendrl server ? Please note, user may have already installed gluster on a node prior to tendrl server installation

**Comment by nthomas-redhat** [comment] 2018-01-24 04:10
@GowthamShanmugam , can you take a look at this?

**Comment by GowthamShanmugam** [comment] 2018-01-24 05:21
@nthomas-redhat i will fix this

**Comment by GowthamShanmugam** [comment] 2018-02-22 08:55
This issue is fixed, please close this @SaravanaStorageNetwork

**Closed** 2018-02-22 09:14 UTC
