### ISSUE TITLE
Add brick status wise counters to graphite

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/monitoring-integration#53] opened 2017-08-31 09:22 UTC
The issue is:

* grafana does countseries to get count of bricks in a given status
* for all stats to be available in gaphite, it takes some time

So given above 2 points, it takes some time for all counters to be correct.
The fix to this will be to push the counter readily rather than deriving it so that the counter is either NA if its not available or a valid counter if it exists.

**Comment by rishubhjain** [comment] 2017-09-18 06:57
@anmolbabu Can you check if the issue is resolved?, and if yes then can we close the issue?

**Comment by anmolbabu** [comment] 2017-09-19 09:05
@rishubhjain Let me know if you have a PR to fix this and if its merged and I can close this..

**Comment by rishubhjain** [comment] 2017-09-19 09:10
@cloudbehl can you confirm if you are receiving all the counters mentioned by @anmolbabu from monitoring-integration

**Comment by cloudbehl** [comment] 2017-09-20 06:55
@rishubhjain Yes, I am receiving all(total, up, down) the brick counter, please go ahead and close the Issue.

**Comment by rishubhjain** [comment] 2017-09-20 06:56
@anmolbabu please close this issue

**Closed** 2017-09-20 08:32 UTC
